// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package sqlgen

type Task struct {
	ID        int64  `json:"_id"`
	Url       string `json:"url"`
	Method    string `json:"method"`
	Namespace string `json:"namespace"`
	Params    []byte `json:"params"`
	Headers   []byte `json:"headers"`
	Body      []byte `json:"body"`
	StartUnix int64  `json:"start_unix"`
	EndUnix   int64  `json:"end_unix"`
	Interval  string `json:"interval"`
}
