// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlgen

type Task struct {
	ID        int64  `json:"_id"`
	Url       string `json:"url"`
	Method    string `json:"method"`
	Namespace string `json:"namespace"`
	Params    []byte `json:"params"`
	Headers   []byte `json:"headers"`
	Body      []byte `json:"body"`
}
