// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlgen

import (
	"context"
)

type Querier interface {
	CreateTask(ctx context.Context, arg CreateTaskParams) (int64, error)
	GetTasks(ctx context.Context) ([]*Task, error)
	GetTasksByNamespace(ctx context.Context, namespace string) ([]*Task, error)
}

var _ Querier = (*Queries)(nil)
