// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package sqlgen

import (
	"context"
)

type Querier interface {
	CreateTask(ctx context.Context, arg CreateTaskParams) (int64, error)
	DeleteTask(ctx context.Context, ID int64) error
	GetActiveTasks(ctx context.Context, endUnix int64) ([]*Task, error)
	GetTaskByID(ctx context.Context, ID int64) (*Task, error)
	GetTasks(ctx context.Context) ([]*Task, error)
	GetTasksByNamespace(ctx context.Context, namespace string) ([]*Task, error)
	UpdateTaskStatus(ctx context.Context, arg UpdateTaskStatusParams) error
}

var _ Querier = (*Queries)(nil)
