services:
  postgres:
    image: postgres
    restart: always
    network_mode: host
    environment:
      POSTGRES_USER: scheduler
      POSTGRES_PASSWORD: scheduler
      POSTGRES_DB: scheduler
    volumes:
      - ./docker:/var/lib/postgresql/data
    ports:
      - 5432:5432

  mongo:
    image: mongo:4.4.21
    restart: always
    network_mode: host
    volumes:
      - ./docker/mongo/db:/data/db