// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package sqlgen

type Task struct {
	ID         int64   `json:"id"`
	Name       string  `json:"name"`
	Desciption *string `json:"desciption"`
}
