// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package sqlgen

import (
	"context"
)

type Querier interface {
	ListTasks(ctx context.Context) ([]*Task, error)
}

var _ Querier = (*Queries)(nil)
