application:
  name: "scheduler"
  port: ":7187"
  env: "development"
database:
  db: "mongo"
  mongodb:
    url: "mongodb://localhost:27017"
  postgres:
    url: "postgres://scheduler:scheduler@localhost:5432/scheduler"
